#  SuperTux
#  Copyright (C) 2021-2021 Sergii Pylypenko <x.pelya.x@gmail.com>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 3
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

name: Android
on:
  workflow_dispatch:
    inputs: {}
    ref: master
    repository: https://github.com/SuperTux/supertux
    sender: SuperTux
    workflow: Android
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set script permissions
        working-directory: ./.github
        run: chmod +x ./scripts/*.sh

      - name: Prepare SDL Android project
        run: |
          ./.github/scripts/clone_dependency.sh libsdl-org/SDL release-2.26.5
          mv ./SDL/android-project/ ./build.android

      - name: Clone dependencies
        working-directory: build.android/app/jni
        run: |
          ../../../.github/scripts/clone_dependency.sh libsdl-org/SDL_image release-2.6.3
          ../../../.github/scripts/clone_dependency.sh SuperTux/SDL_ttf supertux-changes-2018-09-13
          ../../../.github/scripts/clone_dependency.sh boostorg/boost boost-1.82.0
          ../../../.github/scripts/clone_dependency.sh curl/curl curl-8_0_1
          ../../../.github/scripts/clone_dependency.sh fmtlib/fmt 9.1.0
          ../../../.github/scripts/clone_dependency.sh g-truc/glm 0.9.9.8
          ../../../.github/scripts/clone_dependency.sh xiph/vorbis v1.3.7
          ../../../.github/scripts/clone_dependency.sh kcat/openal-soft 1.23.1
          #TODO: i have to take a look into opengl later
          #TODO: i also have to take a look at libpartiozip
          ../../../.github/scripts/clone_dependency.sh SuperTux/physfs release-2.0.3
          ../../../.github/scripts/clone_dependency.sh driedfruit/SDL_SavePNG master
          ../../../.github/scripts/clone_dependency.sh SuperTux/sexp-cpp master
          ../../../.github/scripts/clone_dependency.sh albertodemichelis/squirrel v3.2
          ../../../.github/scripts/clone_dependency.sh SuperTux/tinygettext tinygettext-supertux

      - name: Copy SuperTux Android project files
        run: |
          cp -r -f ./mk/android/* ./build.android/

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.2.0
        with:
          ndk-version: r25c

      - name: Make gradlew executable
        working-directory: build.android
        run: chmod +x ./gradlew

      - name: Generate app APK.
        working-directory: build.android
        run: ./gradlew assembleRelease --stacktrace
